[phases.setup]
aptPkgs = ["libicu-dev"]
cmds = ["docker-php-ext-install intl"]

[phases.build]
cmds = [
    "composer install --optimize-autoloader --no-scripts --no-interaction",
    "cp .env.example .env || true",
    "php artisan key:generate --force || true",
    "php artisan event:cache || true",
    "php artisan route:cache || true",
    "php artisan view:cache || true"
]

[start]
cmd = "php artisan config:clear && php artisan migrate --force && php artisan db:seed --class=RolePermissionSeeder --force && caddy run --config /Caddyfile --adapter caddyfile"
